version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-20.04
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
          sudo systemctl start docker
      - run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - run: |
          docker-compose --version
      - run:
          name: Start Mockoon server
          command: |
            cd examples/moc && docker-compose up -d
            sleep 5