version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: docker:20.10.9
    steps:
      - checkout
      - run:
          name: Start Mockoon server
          command: |
            cd examples/mock && docker-compose up -d
            sleep 5
      - run:
          name: Run tests against Mockoon server
          command: docker ps 
      - run:
          name: Run tests against Mockoon server
          command: docker logs myapi
      - run:
          name: Run tests against Mockoon server
          command: docker exec -it pytest curl -X GET http://myapi:3000/event/list_details