version: "3"
services:
  mockoon:
    build:
     context: .
    container_name: myapi
    command: mockoon-cli start  --data data
    ports:
      - "3000:3000"
    networks:
      demo:
    volumes:
      - type: bind
        source: ../../api/reg-bb-api.json   
        target: /data 
  pytest:
   build:
     context: ../../test/.
   container_name: pytest
   tty: true
   stdin_open: true
   networks:
      demo:


networks:
      demo:
 
