version: "3"
services:
  mockoon:
    image: mockoon/cli:latest
    entrypoint: ["mockoon-cli"]
    command: ["--data-dir", "data", "port", "3000"]
    container_name: myapi
    ports:
      - "3000:3000"
    networks:
      demo:
    volumes:
      - type: bind
        source: ../../api/reg-bb-api.json   
        target: /data 
  pytest:
   build:
     context: ../../test/.
   container_name: pytest
   tty: true
   stdin_open: true
   networks:
      demo:


networks:
      demo:
 
